export const ADD_TODO = 'ADD_TODO';
export const DELETE_TODO = 'DELETE_TODO';
export const COMPLETED_TODO = 'COMPLETED_TODO';
export const UPDATE_TODO = 'UPDATE_TODO';
export const CLEAR_COMPLETED = 'CLEAR_COMPLETED';
export const TOGGLE_COMPLETE_ALL = 'TOGGLE_COMPLETE_ALL';
export const CHANGE_FILTER = 'CHANGE_FILTER';